### ISSUE TITLE
Input parsing errors with spaces in names

### ISSUE THREAD

**Issue by espositoandrea** [matteosecli/pdf2archive#16]
Hi! First of all, thanks for this script: my university has the same requirements for some documents and it's a blessing.

I have an issue with the parsing of the input from the CLI: when a file name has spaces, it gets truncated to the first word: for example by having "Tesi Andrea Esposito.pdf", the tool only uses "Tesi" as its input file.

I think that this is due to the ad-hoc input parsing method. I think that re-implementing it using POSIX's [`getopts`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/getopts.html) would be better, although we'll lose the "long" format of the option names. We could also try to modify the current code to accept names with spaces.

I'm willing to work on this issue: would you consider it if I opened a PR? If so, would you prefer going towards the standard POSIX route or keeping and fixing the ad-hoc route?

Thanks again

**Comment by matteosecli** [comment]
Ciao @espositoandrea, thanks for reporting!

As of now, I would prefer to keep backward compatibility with the options; changing the command-line syntax out of the blue would break every existing script using `pdf2archive` and it's something I would consider at most for a new major version.

So as far as the input options are concerned, I would still go with the existing machinery. I've probably been too sloppy when using variables without quotes here and there, so I've tried to push a quick fix in https://github.com/matteosecli/pdf2archive/commit/08a671b082c304f5757aa67d51a0bfac031ae7e7; can you confirm whether that solves the issue? Otherwise I would be more than happy to accept a PR. 🙂

**Comment by espositoandrea** [comment]
It works as intended. Thank you and sorry for the over-engineering I did there 😅

**Comment by matteosecli** [comment]
That's great, no worries! 😉 

Sorry for the sloppiness in the script! 😅
